image: Visual Studio 2017
build: off
test: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'

skip_branch_with_pr: true
branches:
  only:
    - master

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - "python -m pip install pytest parse toml"
  - "python -m pip install -e ."

build: off

test_script:
  - "python -m hatch conda ~\\miniconda"
  - "for /f %%i in ('python -m hatch conda --show ~/miniconda') do set PATH=%PATH%;%%i"
  - "python -m pytest"
