language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: pypy3
      env: TOXENV=pypy3
    - language: generic
      os: osx
      osx_image: xcode10.1
      env: TOXENV=py37
      before_install:
        - brew update
        - pip uninstall virtualenv || true
        - brew upgrade python
        - pip3 install -U virtualenv
        - virtualenv env
        - source env/bin/activate
  allow_failures:
    - os: osx

install:
  - pip install tox codecov
  - pip install -e .

script:
  - hatch conda ~/miniconda
  - export PATH="$PATH:$(hatch conda --show ~/miniconda)"
  - tox

after_success:
  - codecov
